// Generated by gencpp from file learning_communication/WordCount.msg
// DO NOT EDIT!


#ifndef LEARNING_COMMUNICATION_MESSAGE_WORDCOUNT_H
#define LEARNING_COMMUNICATION_MESSAGE_WORDCOUNT_H

#include <ros/service_traits.h>


#include <learning_communication/WordCountRequest.h>
#include <learning_communication/WordCountResponse.h>


namespace learning_communication
{

struct WordCount
{

typedef WordCountRequest Request;
typedef WordCountResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WordCount
} // namespace learning_communication


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::learning_communication::WordCount > {
  static const char* value()
  {
    return "58903d21a3264f3408d79ba79e9f7c7e";
  }

  static const char* value(const ::learning_communication::WordCount&) { return value(); }
};

template<>
struct DataType< ::learning_communication::WordCount > {
  static const char* value()
  {
    return "learning_communication/WordCount";
  }

  static const char* value(const ::learning_communication::WordCount&) { return value(); }
};


// service_traits::MD5Sum< ::learning_communication::WordCountRequest> should match 
// service_traits::MD5Sum< ::learning_communication::WordCount > 
template<>
struct MD5Sum< ::learning_communication::WordCountRequest>
{
  static const char* value()
  {
    return MD5Sum< ::learning_communication::WordCount >::value();
  }
  static const char* value(const ::learning_communication::WordCountRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::learning_communication::WordCountRequest> should match 
// service_traits::DataType< ::learning_communication::WordCount > 
template<>
struct DataType< ::learning_communication::WordCountRequest>
{
  static const char* value()
  {
    return DataType< ::learning_communication::WordCount >::value();
  }
  static const char* value(const ::learning_communication::WordCountRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::learning_communication::WordCountResponse> should match 
// service_traits::MD5Sum< ::learning_communication::WordCount > 
template<>
struct MD5Sum< ::learning_communication::WordCountResponse>
{
  static const char* value()
  {
    return MD5Sum< ::learning_communication::WordCount >::value();
  }
  static const char* value(const ::learning_communication::WordCountResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::learning_communication::WordCountResponse> should match 
// service_traits::DataType< ::learning_communication::WordCount > 
template<>
struct DataType< ::learning_communication::WordCountResponse>
{
  static const char* value()
  {
    return DataType< ::learning_communication::WordCount >::value();
  }
  static const char* value(const ::learning_communication::WordCountResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LEARNING_COMMUNICATION_MESSAGE_WORDCOUNT_H
